#!/bin/bash
SDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
source $SDIR/jh_config
# Purpose:
# wrapper script to stop users job.
# The JupyterHub server calls this wrapper script. The job id of the user is in $1 (transfers by the JupyterHub server extracted at start time)

# get information from given job $1
jobid=$1
job_owner=$(${cmd_job_owner[@]})
job_batch=$(${cmd_job_batchfile[@]} | ${cmd_job_batchfile_filter[@]})

function cleanup () {

    [[ -d $webdav_mount_dir ]] && rmdir $webdav_mount_dir && create_log_entry "DEBUG" "[WEBDAV] Deleted WebDAV-Directory $webdav_mount_dir"
	rm $job_batch

	create_log_entry "DEBUG" "[Kill] Successfully cleaned up the home directory for user $job_owner"
}

function stop_instance () {

	create_log_entry "INFO" " [Kill] Stopping job for user $job_owner with ID $jobid ..."
	create_log_entry "DEBUG" "[Kill] Now cleaning up the job directory for user $job_owner"
	cleanup

	# Finally kill the job
	cmd_kill_job+=("$jobid")
	${cmd_kill_job[@]}

	create_log_entry "DEBUG" "[Kill] Job for user $job_owner with ID $jobid stopped!"	
}

stop_instance
