#!/bin/bash
# Purpose: This file is required to make the JupyterHub API locally available on port 8083 and the notebook server locally on the JupyterHub

function build_tunnel () {

    eval $(TMPDIR=/tmp/ ssh-agent)
    tmp_sshk=$(mktemp)
    echo "$SSH_PRIV_KEY" > $tmp_sshk
    chmod 600 $tmp_sshk
    ssh-add $tmp_sshk

    # Build SSH tunnel so that the JupyterHub can reach the notebook server running on a compute node
    ssh -i $tmp_sshk -o StrictHostKeyChecking=no -fN -R $JUPYTER_PORT:127.0.0.1:$JUPYTER_PORT $SSH_TUNNEL_USER@$SSH_JUPYTERHUB_IP

    if $SSH_TUNNEL_API; then
    curl http://127.0.0.1:8083/hub/api &> /dev/null
        if [[ ! $? -eq 0 ]]; then
            # API on compute node is not available
            # jh_config: $external_hub_url - JupyterHub API URL
            # Why 8083 and not default 8081? The most HPC systems are using Bright as Cluster Management Software whichs needs port 8081 :-)
            ssh -i $tmp_sshk -o StrictHostKeyChecking=no -fN -L $SSH_TUNNEL_API_PORT:127.0.0.1:8081 $SSH_TUNNEL_USER@$SSH_JUPYTERHUB_IP
        fi
    fi
    rm -f $tmp_sshk
    unset -v tmp_sshk
    export SSH_PRIV_KEY=":-P"
}

build_tunnel
