#!/bin/bash
SDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
[[ ! -f $SDIR/jh_config ]] && >&2 echo "All wrapper scripts should be placed in the same directory!" && exit 1
source $SDIR/jh_config
# Author: Marcel-Brian Wilkowsky
# Purpose: Just a script to show todays log information

LAST_LN=10
LAST=false
FOLLOW=false

today=$(date $logging_save_date_fmt)

function show_log () {

	if [[ $FOLLOW == true && $LAST == true ]]; then
		tail -fn $LAST_LN $log_dir/$today
	elif [[ $LAST == true ]]; then
		tail -n $LAST_LN $log_dir/$today
	elif [[ $FOLLOW == true ]]; then
		tail -f $log_dir/$today
	else
		cat $log_dir/$today
	fi
}

function check_logging () {

    if $enable_logging; then
        if [[ !  -f $log_dir/$today ]]; then
            >&2 echo "Hmm... File $log_dir/$today does not exists!"
            exit 1
        else
            # Finally show log
            show_log
        fi
    else
       >&2 echo "Well... Logging is disabled! Activate logging by setting enable_logging in jh_config to true"
       exit 1
    fi
}

while getopts :fl: OPTION; do

	case "$OPTION" in
	f)
	FOLLOW=true
	;;
	l)
	LAST=true
	[[ ! $2 =~ ^[0-9]+$ ]] && echo "Error: Option -l: a number is requied" && exit 1
	[[ -z $2 ]] && break || LAST_LN=$2
	;;
	*)
	echo "Usage: $0 [-f (follow)] [-l number (tell last how many lines to show]" && exit 1;;
	esac
done
[[ -z $OPTIND ]] && shift $OPTIND-1

check_logging
