Bootstrap: docker
From: debian

%post
    
    USER_UID=77478

    ##### BASE INSTALLATION #####
    apt update
    apt install -y python3 python3-pip vim
    python3 -m pip install notebook batchspawner jupyterhub

    ##### NEW DIRECTORIES #####
    mkdir /notebooks/
    mkdir /userhome/

    ##### SET DIRECTORIES TO UID WHO RUNS THE CONTAINER #####
    chown -R $USER_UID /notebooks/
    chown -R $USER_UID /opt/
    chown -R $USER_UID /userhome/
    chown -R $USER_UID /usr/

    ##### GLOBAL JUPYTER CONFIG FILE #####
    mkdir -p /etc/jupyter/
    touch /etc/jupyter/jupyter_notebook_config.py
    echo "c.NotebookApp.notebook_dir='/notebooks'" > /etc/jupyter/jupyter_notebook_config.py
